{% set name = "widgetsnbextension" %}
{% set version = "3.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/widgetsnbextension-{{ version }}.tar.gz
  sha256: cc370876baee1d23d4c506c798ab7d08c355133c9a5e81474159ff75877593df

build:
  number: 0
  skip: True  # [py<36 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - notebook >=4.4.1

test:
  imports:
    - widgetsnbextension
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://ipython.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Interactive Widgets for Jupyter
  description: |
    Interactive HTML widgets for Jupyter notebooks.
  doc_url: https://pypi.org/project/widgetsnbextension/
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/python/widgetsnbextension

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
    - ocefpaf
