{% set version = "3.0.0" %}
{% set sha256 = "da2d22012cdf1450ed098627924d116232dd53e259e3a54f4f79cd5b52cbaf99" %}

package:
    name: widgetsnbextension
    version: {{ version }}

source:
    fn: widgetsnbextension-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - notebook >=4.4.1
    run:
        - python
        - notebook >=4.4.1

test:
    imports:
        - widgetsnbextension

about:
    home: http://ipython.org
    license: BSD 3-clause
    summary: Interactive Widgets for Jupyter

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
