{% set name = "widgetsnbextension" %}
{% set version = "4.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3629b04e3edb893212df862038c7232f62973373869db5084aed739b437b5af

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<37]

requirements:
  host:
    - python
    - jupyter-packaging >=0.10,<2
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - widgetsnbextension
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Interactive Widgets for Jupyter
  description: |
    Interactive Jupyter widgets for the classic Jupyter Notebook application. 
    This package provides the necessary JavaScript controls in the Jupyter Notebook that communicate with the widget objects in the kernel.
  doc_url: https://pypi.org/pypi/widgetsnbextension
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/main/python/widgetsnbextension

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
    - ocefpaf
    - bollwyvl
    