{% set name = "widgetsnbextension" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/widgetsnbextension-{{ version }}.tar.gz
  sha256: e84a7a9fcb9baf3d57106e184a7389a8f8eb935bf741a5eb9d60aa18cc029a80

build:
  number: 0
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - notebook >=4.4.1

test:
  imports:
    - widgetsnbextension
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://ipython.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Interactive Widgets for Jupyter
  description: |
    Interactive HTML widgets for Jupyter notebooks.
  doc_url: https://pypi.python.org/pypi/widgetsnbextension
  dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/python/widgetsnbextension

extra:
  recipe-maintainers:
    - jasongrout
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - pbugnion
    - ocefpaf
