travis:
  secure:
    BINSTAR_TOKEN: pzJIaIJAmBFROFDFoxb0Lvf2BcmZBEsjD002ppIm6PsEGGxH1Ist3BW3MFb8NTMES40Z+Ij1Mqg+ML0uszgi4ZXYGQCaHxMYPnWA/ilzjvrXaa8X5AEKwq5Q56DjDbe7o5w2fXQE95WVhDz65FNQIlBUCIDS+IQmWPpfCbHMDbUdgtQaUWoHzgtjvbO5U7U50wVL84pj1dBUcl3AT+rmMsnsXZdG4CmrOipI3qQeyL9/4K6cafk6OeJZsLZf0mssn1D04S1HCAfZphsmuBFj+9Ay/BglcGsoTYXQEBIbpR+F89te5i8I+VRyjTjqwxa80KwyGfPyqgjMabOIkJ7E5S2UypuEFtivTB3lcYTDG8XGQK74pVnDFBofjzPuSqB1sfjiLIY8jS1kxvqxyqnut++473f5/nz0Cxaql48euR/dz6CgEi83qLP6iqd3rh6HlFXFPqrhngiPfE9CAKe5sPPf9gbe9q43kNZa0Hat/cr4pd9I5yJQO8LT7aO8AriNv6fbDH3XngJ0J1OArrzKMoSoDLw9B3OWMO3KQFpETXF+1nBheT/DSiTxr02iCE5lnnBVM3PEUuNg4eazGPJyDGhfGp9xo0BV6fZI7GjUwF17PYj3tgbfdKWlWoA1jSyRFAOez614pyDJ+lfELqODW7JPUWVgw9Jcy3o6XcksUQY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
